apiVersion: v1
kind: Pod
metadata:
  name: curl-jane
spec:
  serviceAccountName: jane
  containers:
    - name: main
      image: tutum/curl
      command: ["sleep", "9999999"]
    - name: ambassador
      image: luksa/kubectl-proxy:1.6.2

---
apiVersion: v1
kind: Pod
metadata:
  name: curl-ken
spec:
  serviceAccountName: ken
  containers:
    - name: main
      image: tutum/curl
      command: ["sleep", "9999999"]
    - name: ambassador
      image: luksa/kubectl-proxy:1.6.2
