apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: prom-admin
  namespace: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prom-rbac
  namespace: prometheus
subjects:
  - kind: ServiceAccount
    name: carol
    namespace: prometheus
roleRef:
  kind: ClusterRole
  name: prom-admin
  apiGroup: rbac.authorization.k8s.io
