apiVersion: v1
kind: Pod
metadata:
  name: curl-admin
spec:
  serviceAccountName: carol
  automountServiceAccountToken: true
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: luksa/kubectl-proxy:1.6.2
