apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-bob
spec:
  serviceAccountName: bob
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: luksa/kubectl-proxy:1.6.2
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
spec:
  serviceAccountName: dave
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: luksa/kubectl-proxy:1.6.2
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-admin
spec:
  serviceAccountName: default
  automountServiceAccountToken: true
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: luksa/kubectl-proxy:1.6.2
